### ISSUE TITLE
Proxy limit kontrolünde düzeltme

### ISSUE THREAD

**Issue by gitcem** [GoTurkiye/training#9]
https://github.com/GoTurkiye/training/blob/86e237f7ec9688cde56b3c2ad94c34b5afde41f7/103-http/proxy/limit.go#L45

Merhaba, alıntıladığım function'da counter map'indeki ilgili elemanın değerlerini resetleyen bir logic'e ihtiyaç var diye düşünüyorum. Kodun bu halinde, sayı limiti dolmayıp, TTL duration'dan fazla bir zaman geçerse if'e ve else-if'e girmeden sürekli yoluna devam eder.

If'te sadece sayı limiti kontrolünü bırakıp, TTL kontrolünün if'in içine girince yapılması; TTL aşılmadıysa 429 dönülmesi, aşıldıysa counter[path] elemanının count=1 (o anda gelen isteği reddetmeyeceğimiz için) ve ttl=time.Now().Add(p.ttl) olarak güncellenmesi doğru olur.

**Comment by gunerhuseyin** [comment]
@gitcem guzel tespit 👍 burayi duzelten bir pr acabilir misin?

**Comment by gitcem** [comment]
Gönderdim şimdi 👍 #10
